### ISSUE TITLE
Difficulty getting it started up due to unhandled runtime error

### ISSUE THREAD

**Issue by classicrob** [kasrak/feedpaper#1]
I ran the npm install command as specified in the readme, but ended up with this error. Thoughts? I also tried installing sqlite globally and then linking it in the client and app folders, but that didn't work either.

<img width="747" alt="CleanShot 2023-04-20 at 10 10 16@2x" src="https://user-images.githubusercontent.com/46608303/233439120-90b38723-0546-4cea-8844-0ccf2d003909.png">

Uncaught Exception:
Error: Cannot find module '/usr/local/lib/node_modules/sqlite3/lib/binding/napi-v6-darwin-unknown-arm64/node_sqlite3.node'
Require stack:
- /usr/local/lib/node_modules/sqlite3/lib/sqlite3-binding.js
- /usr/local/lib/node_modules/sqlite3/lib/sqlite3.js
- /../feedpaper/app/dist/main/main.js
- /../feedpaper/app/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js
- 
at Module._resolveFilename (node:internal/modules/cjs/loader:963:15)
at n._resolveFilename (node:electron/js2c/browser_init:2:109751)
at Module._load (node:internal/modules/cjs/loader:811:27)
at f._load (node:electron/js2c/asar_bundle:2:13330)
at Module.require (node:internal/modules/cjs/loader:1035:19)
at require (node:internal/modules/cjs/helpers:102:18)
at Object.<anonymous> (/usr/local/lib/node_modules/sqlite3/lib/sqlite3-binding.js:4:17)
at Module._compile (node:internal/modules/cjs/loader:1141:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
at Module.load (node:internal/modules/cjs/loader:1011:32)

**Comment by kasrak** [comment]
Hm, you shouldn't need to install sqlite globally. What node version are you on (`node -v`)? FWIW I'm on v16.14.0

And were there any errors when you run `npm install --prefix=app`?

**Comment by classicrob** [comment]
No errors, but tried running it again. Same issue. Also switched from v19.4.0 to v16.14.0, no luck.

```
npm install --prefix=app && npm install --prefix=client

up to date, audited 663 packages in 2s

79 packages are looking for funding
  run `npm fund` for details

6 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

up to date, audited 389 packages in 880ms

116 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

**Comment by classicrob** [comment]
AHA! Idk what the issue was, but I deleted the repo and recloned it, with your version of node, and it works now. Thanks!

**Comment by kasrak** [comment]
Strange! I'm glad it eventually worked!
